### ISSUE TITLE
Pass the artifact checksum path to the alvariumAnnotate() method as a parameter

### ISSUE THREAD

**Issue by Ali-Amin** [Ali-Amin/alvarium-pipelines#1]
The `alvariumAnnotate()` method as is assumes the checksum file path for the artifacts generated at a specific location under `$JENKINS_HOME`. More flexibility might be of value by passing an _optional_ path parameter for these checksums which defaults to the existing value.

**Comment by o-eissa** [comment]
test

**Comment by o-eissa** [comment]
I'm pending on Merge of #5 to rebase on the new method signatures.
Aslo, should we follow the same implementation as done for the artifactPath or there can be a better approach?
I though about passing a Map of optional inputs
```groovy
def call(
    List<String> annotatorKinds,
    Map<String, String> optionalInputs = [:],
    SdkInfo sdkInfo,
    Logger logger
)
```
then calling as follows:
```groovy
def myMap = [ "artifactPath": "dummy/path",
              "checksumPath": "dummy/path",
              "sourceCodeChecksumPath": "dummy/path"]
                    
alvariumAnnotate(annotatorKinds,myMap)
```
We would be defaulting to the already coded paths if any of the paths wasn't provided.

All of the above also applies to #2.
